import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import glob
from pathlib import Path
from settings import OUTPUT_DIR, NUM_NODES
import matplotlib

# Check if backend is interactive
is_interactive = matplotlib.get_backend() in matplotlib.rcsetup.interactive_bk

OUTPUT_DIR = "/Users/amirosein/Desktop/project/PythonProjects/srb/thesis/main/output"


def load_batch_data_from_csvs(csv_directory=None):
    """
    Load data from multiple CSV files generated by batch runs.

    Args:
        csv_directory: Directory containing CSV files. If None, uses OUTPUT_DIR/logs

    Returns:
        dict: Dictionary with batch_size as key and DataFrame as value
    """
    if csv_directory is None:
        csv_directory = os.path.join(OUTPUT_DIR, "logs")

    # Find all CSV files from batch runs
    csv_pattern = os.path.join(csv_directory, "metrics_log_*_*_*_*_*_*.csv")
    csv_files = glob.glob(csv_pattern)

    batch_data = {}

    for csv_file in csv_files:
        try:
            # Extract FHE_INTERVAL from filename
            filename = os.path.basename(csv_file)
            parts = filename.replace(".csv", "").split("_")

            if len(parts) >= 7:
                fhe_interval = int(parts[-2])  # FHE_INTERVAL is second to last

                # Read CSV data
                df = pd.read_csv(csv_file)
                df["batch_size"] = fhe_interval  # Add batch size column
                batch_data[fhe_interval] = df

                print(f"Loaded batch {fhe_interval}: {len(df)} nodes")

        except Exception as e:
            print(f"Error processing {csv_file}: {e}")

    return batch_data


def analyze_batch_efficiency(batch_data):
    """
    Analyze energy and latency efficiency across batch sizes.

    Args:
        batch_data: Dictionary from load_batch_data_from_csvs()

    Returns:
        tuple: (summary_df, optimal_energy_batch, optimal_latency_batch)
    """
    summary_data = []

    for batch_size in sorted(batch_data.keys()):
        df = batch_data[batch_size]

        # Calculate statistics for this batch
        stats = {
            "batch_size": batch_size,
            "avg_latency": df["latency_ms"].mean(),
            "std_latency": df["latency_ms"].std(),
            "min_latency": df["latency_ms"].min(),
            "max_latency": df["latency_ms"].max(),
            "avg_energy": df["energy"].mean(),
            "std_energy": df["energy"].std(),
            "min_energy": df["energy"].min(),
            "max_energy": df["energy"].max(),
            "total_energy": df["energy"].sum(),
            "avg_battery": df["battery"].mean(),
            "min_battery": df["battery"].min(),
            "node_count": len(df),
        }
        summary_data.append(stats)

    summary_df = pd.DataFrame(summary_data)

    # Find optimal batch sizes
    optimal_energy_batch = summary_df.loc[
        summary_df["avg_energy"].idxmin(), "batch_size"
    ]
    optimal_latency_batch = summary_df.loc[
        summary_df["avg_latency"].idxmin(), "batch_size"
    ]

    return summary_df, optimal_energy_batch, optimal_latency_batch


def plot_comprehensive_batch_analysis(
    batch_data=None, csv_directory=None, save_plots=True
):
    """
    Create comprehensive plots showing energy and latency analysis across batch sizes.

    Args:
        batch_data: Pre-loaded batch data. If None, loads from csv_directory
        csv_directory: Directory containing CSV files
        save_plots: Whether to save plots to files
    """
    # Load data if not provided
    if batch_data is None:
        batch_data = load_batch_data_from_csvs(csv_directory)

    if not batch_data:
        print("No batch data found!")
        return

    # Analyze efficiency
    summary_df, optimal_energy_batch, optimal_latency_batch = analyze_batch_efficiency(
        batch_data
    )

    print(f"\n=== BATCH EFFICIENCY ANALYSIS ===")
    print(f"Optimal batch size for ENERGY efficiency: {optimal_energy_batch}")
    print(f"Optimal batch size for LATENCY efficiency: {optimal_latency_batch}")
    print(
        f"Energy at optimal batch: {summary_df[summary_df['batch_size']==optimal_energy_batch]['avg_energy'].iloc[0]:.3f} mJ"
    )
    print(
        f"Latency at optimal batch: {summary_df[summary_df['batch_size']==optimal_latency_batch]['avg_latency'].iloc[0]:.2f} ms"
    )

    # Create plots directory
    if save_plots:
        plots_dir = os.path.join(OUTPUT_DIR, "plots")
        os.makedirs(plots_dir, exist_ok=True)

    # Check if we're in an interactive backend
    is_interactive = matplotlib.get_backend() in matplotlib.rcsetup.interactive_bk

    # ============ PLOT 1: Individual Node Performance by Batch Size ============
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 12))

    # Energy consumption per node
    batch_sizes = sorted(batch_data.keys())
    colors = plt.cm.viridis(np.linspace(0, 1, len(batch_sizes)))

    for i, batch_size in enumerate(batch_sizes):
        df = batch_data[batch_size]
        ax1.scatter(
            [batch_size] * len(df),
            df["energy"],
            alpha=0.6,
            color=colors[i],
            s=50,
            label=f"Batch {batch_size}",
        )

    # Add average line
    ax1.plot(
        batch_sizes,
        summary_df["avg_energy"],
        linewidth=2,
        markersize=8,
        label="Average Energy",
        color="red",
        marker="o",
    )

    # Mark optimal point
    ax1.axvline(
        x=optimal_energy_batch,
        color="green",
        linestyle="--",
        linewidth=2,
        label=f"Optimal Energy (Batch {optimal_energy_batch})",
    )

    ax1.set_xlabel("Batch Size (FHE Interval)")
    ax1.set_ylabel("Energy Consumption (mJ)")
    ax1.set_title("Energy Consumption per Node Across Batch Sizes")
    ax1.grid(True, alpha=0.3)
    ax1.legend(bbox_to_anchor=(1.05, 1), loc="upper left")

    # Latency per node
    for i, batch_size in enumerate(batch_sizes):
        df = batch_data[batch_size]
        ax2.scatter(
            [batch_size] * len(df), df["latency_ms"], alpha=0.6, color=colors[i], s=50
        )

    # Add average line
    ax2.plot(
        batch_sizes,
        summary_df["avg_latency"],
        linewidth=2,
        markersize=8,
        label="Average Latency",
        color="blue",
        marker="o",
    )

    # Mark optimal point
    ax2.axvline(
        x=optimal_latency_batch,
        color="orange",
        linestyle="--",
        linewidth=2,
        label=f"Optimal Latency (Batch {optimal_latency_batch})",
    )

    ax2.set_xlabel("Batch Size (FHE Interval)")
    ax2.set_ylabel("Latency (ms)")
    ax2.set_title("Latency per Node Across Batch Sizes")
    ax2.grid(True, alpha=0.3)
    ax2.legend()

    plt.tight_layout()
    if save_plots:
        plt.savefig(
            os.path.join(
                plots_dir, f"individual_node_performance_{NUM_NODES}nodes.png"
            ),
            dpi=300,
            bbox_inches="tight",
        )
        plt.close(fig)
    elif is_interactive:
        plt.show()

    # ============ PLOT 2: Summary Statistics with Error Bars ============
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    # Energy efficiency plot
    ax1.errorbar(
        summary_df["batch_size"],
        summary_df["avg_energy"],
        yerr=summary_df["std_energy"],
        fmt="o-",
        capsize=5,
        capthick=2,
        color="purple",
        linewidth=2,
        markersize=8,
    )
    ax1.fill_between(
        summary_df["batch_size"],
        summary_df["avg_energy"] - summary_df["std_energy"],
        summary_df["avg_energy"] + summary_df["std_energy"],
        alpha=0.2,
        color="purple",
    )

    # Mark optimal point
    optimal_energy_row = summary_df[
        summary_df["batch_size"] == optimal_energy_batch
    ].iloc[0]
    ax1.scatter(
        [optimal_energy_batch],
        [optimal_energy_row["avg_energy"]],
        color="green",
        s=150,
        marker="*",
        zorder=5,
        label=f"Optimal: Batch {optimal_energy_batch}",
    )

    ax1.set_xlabel("Batch Size (FHE Interval)")
    ax1.set_ylabel("Average Energy Consumption (mJ)")
    ax1.set_title("Energy Efficiency Analysis")
    ax1.grid(True, alpha=0.3)
    ax1.legend()

    # Latency efficiency plot
    ax2.errorbar(
        summary_df["batch_size"],
        summary_df["avg_latency"],
        yerr=summary_df["std_latency"],
        fmt="o-",
        capsize=5,
        capthick=2,
        color="blue",
        linewidth=2,
        markersize=8,
    )
    ax2.fill_between(
        summary_df["batch_size"],
        summary_df["avg_latency"] - summary_df["std_latency"],
        summary_df["avg_latency"] + summary_df["std_latency"],
        alpha=0.2,
        color="blue",
    )

    # Mark optimal point
    optimal_latency_row = summary_df[
        summary_df["batch_size"] == optimal_latency_batch
    ].iloc[0]
    ax2.scatter(
        [optimal_latency_batch],
        [optimal_latency_row["avg_latency"]],
        color="orange",
        s=150,
        marker="*",
        zorder=5,
        label=f"Optimal: Batch {optimal_latency_batch}",
    )

    ax2.set_xlabel("Batch Size (FHE Interval)")
    ax2.set_ylabel("Average Latency (ms)")
    ax2.set_title("Latency Efficiency Analysis")
    ax2.grid(True, alpha=0.3)
    ax2.legend()

    plt.tight_layout()
    if save_plots:
        plt.savefig(
            os.path.join(plots_dir, f"efficiency_analysis_{NUM_NODES}nodes.png"),
            dpi=300,
            bbox_inches="tight",
        )
        plt.close(fig)
    elif is_interactive:
        plt.show()

    # ============ PLOT 3: Combined Efficiency Trade-off ============
    fig, ax = plt.subplots(1, 1, figsize=(12, 8))

    # Normalize metrics for comparison (0-1 scale)
    norm_energy = (summary_df["avg_energy"] - summary_df["avg_energy"].min()) / (
        summary_df["avg_energy"].max() - summary_df["avg_energy"].min()
    )
    norm_latency = (summary_df["avg_latency"] - summary_df["avg_latency"].min()) / (
        summary_df["avg_latency"].max() - summary_df["avg_latency"].min()
    )

    # Plot normalized metrics
    ax.plot(
        summary_df["batch_size"],
        norm_energy,
        "o-",
        linewidth=3,
        markersize=8,
        color="purple",
        label="Normalized Energy",
    )
    ax.plot(
        summary_df["batch_size"],
        norm_latency,
        "s-",
        linewidth=3,
        markersize=8,
        color="blue",
        label="Normalized Latency",
    )

    # Combined score (equal weights)
    combined_score = (norm_energy + norm_latency) / 2
    ax.plot(
        summary_df["batch_size"],
        combined_score,
        "^-",
        linewidth=3,
        markersize=8,
        color="red",
        label="Combined Score",
    )

    # Find optimal combined point
    optimal_combined_batch = summary_df.loc[combined_score.idxmin(), "batch_size"]
    ax.axvline(
        x=optimal_combined_batch,
        color="red",
        linestyle="--",
        linewidth=2,
        label=f"Optimal Combined (Batch {optimal_combined_batch})",
    )

    # Mark individual optimal points
    ax.axvline(
        x=optimal_energy_batch,
        color="purple",
        linestyle=":",
        alpha=0.7,
        label=f"Energy Optimal (Batch {optimal_energy_batch})",
    )
    ax.axvline(
        x=optimal_latency_batch,
        color="blue",
        linestyle=":",
        alpha=0.7,
        label=f"Latency Optimal (Batch {optimal_latency_batch})",
    )

    ax.set_xlabel("Batch Size (FHE Interval)")
    ax.set_ylabel("Normalized Score (0=Best, 1=Worst)")
    ax.set_title("Combined Efficiency Trade-off Analysis")
    ax.grid(True, alpha=0.3)
    ax.legend()
    ax.set_ylim(-0.05, 1.05)

    plt.tight_layout()
    if save_plots:
        plt.savefig(
            os.path.join(plots_dir, f"combined_tradeoff_{NUM_NODES}nodes.png"),
            dpi=300,
            bbox_inches="tight",
        )
        plt.close(fig)
    elif is_interactive:
        plt.show()

    # ============ PLOT 4: Battery Impact Analysis ============
    fig, ax = plt.subplots(1, 1, figsize=(12, 6))

    # Box plot of battery levels by batch size
    battery_by_batch = [batch_data[batch]["battery"].values for batch in batch_sizes]

    # Use tick_labels instead of labels to avoid deprecation warning
    box_plot = ax.boxplot(battery_by_batch, tick_labels=batch_sizes, patch_artist=True)

    # Color the boxes
    colors = plt.cm.RdYlGn(np.linspace(0.2, 0.8, len(batch_sizes)))
    for patch, color in zip(box_plot["boxes"], colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.7)

    ax.set_xlabel("Batch Size (FHE Interval)")
    ax.set_ylabel("Battery Level (%)")
    ax.set_title("Battery Levels Distribution by Batch Size")
    ax.grid(True, alpha=0.3)

    # Add horizontal line at battery threshold (if available)
    # ax.axhline(y=20, color='red', linestyle='--', alpha=0.7, label='Battery Threshold')
    # ax.legend()

    plt.tight_layout()
    if save_plots:
        plt.savefig(
            os.path.join(plots_dir, f"battery_analysis_{NUM_NODES}nodes.png"),
            dpi=300,
            bbox_inches="tight",
        )
        plt.close(fig)
    elif is_interactive:
        plt.show()

    # ============ SAVE SUMMARY DATA ============
    if save_plots:
        summary_file = os.path.join(OUTPUT_DIR, "batch_efficiency_summary.csv")
        summary_df.to_csv(summary_file, index=False)
        print(f"\nSummary data saved to: {summary_file}")

    # Print detailed summary
    print(f"\n=== DETAILED EFFICIENCY SUMMARY ===")
    print(summary_df.round(3))

    return summary_df, optimal_energy_batch, optimal_latency_batch


# Convenience function to run the analysis
def run_batch_analysis(csv_directory=None):
    """
    Main function to run the complete batch analysis.

    Args:
        csv_directory: Directory containing CSV files. If None, uses OUTPUT_DIR/logs

    Returns:
        tuple: (summary_df, optimal_energy_batch, optimal_latency_batch)
    """
    print("Starting comprehensive batch analysis...")
    return plot_comprehensive_batch_analysis(csv_directory=csv_directory)


# Example usage
if __name__ == "__main__":
    # Run the analysis
    summary, opt_energy, opt_latency = run_batch_analysis()

    print(f"\n=== FINAL RECOMMENDATIONS ===")
    print(f"For ENERGY efficiency, use batch size: {opt_energy}")
    print(f"For LATENCY efficiency, use batch size: {opt_latency}")

    if opt_energy == opt_latency:
        print(f"Batch size {opt_energy} is optimal for both energy and latency!")
    else:
        print(f"Trade-off exists between energy and latency optimization.")
